name: Lint -> Integration Tests -> Deploy

on:
  push:
    branches:    
      - main
      - dev
      - 'releases/**'
    tags:        
      - v1
      - v1.*
  pull_request:
    branches:    
      - main
      - dev
      - 'releases/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAIL_SERVICE_API_KEY: ${{secrets.MAIL_SERVICE_API_KEY}}
      MAIL_SERVICE_SENDER: ${{secrets.MAIL_SERVICE_SENDER}}
      VAPID_PUBLIC_KEY: ${{secrets.VAPID_PUBLIC_KEY}}
      VAPID_PRIVATE_KEY: ${{secrets.VAPID_PRIVATE_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Start docker stack
        run: docker-compose -f ./docker-compose.test.yaml up --build --exit-code-from api api
      - name: Docker status mongo setup
        run: docker-compose -f ./docker-compose.test.yaml logs -f --tail 100 mongo-setup
      - name: Docker status mongo1
        run: docker-compose -f ./docker-compose.test.yaml logs -f --tail 100 mongo1
      - name: Docker status mongo2
        run: docker-compose -f ./docker-compose.test.yaml logs -f --tail 100 mongo2
      - name: Docker status mongo3
        run: docker-compose -f ./docker-compose.test.yaml logs -f --tail 100 mongo3
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deployed successfully!"